### PR TITLE
12 ui unit test

### LINKED ISSUE #12: UI Unit Test
Test whether the PaginatableList is rendering properly.
- [ ] When onRenderItem props exist, make sure the value of onRenderItem is called properly to render list cells.
- [ ] When onRenderEmptyStatus props exist, test if the value of onRenderEmptyStatus is called properly to render empty status of the list.

### PR DESCRIPTION
**Pull request by sunkibaek**
Closes #12 

In this PR, I have tried to set up a testing environment for RN components and add a few component tests.

I tried to follow the scenarios laid out in #12 but let me know if I am missing anything.

If this setup is satisfactory we can go on and add more similar tests for the components.

### CODE REVIEW

**Comment by fpena** [comment]
Hey @sunkibaek . Thanks for this. We'll review it soon!

**Comment by BeckyWu220** [comment]
@sunkibaek Thanks for your PR. We've reviewed it through. Generally, the PR looks pretty good and we got your idea of creating snapshots to prevent future code changes the UI unconsciously. Here are a few suggestions if you could work on before we merge the PR.

**Comment by BeckyWu220** [comment]
Hi, @sunkibaek. Thanks for submitting the PR. We had reviewed it through and got your intention to create snapshots to avoid unconscious UI changes by the future code. Here are a few suggestions that we would appreciate you to work on before merging it.

1. In package.json file, please add `"modulePathIngnorePatterns"` in the `"jest"`, make its value `"/PaginatableListExample"`. This will limit the test scope to only the library code instead of both library code and example code.

2. Please rename the `index.test.js` into `ui.test.js` and regenerate the snapshot if necessary. This will help us split the test code properly. Later, we could have API related test, Redux Store related test, and so forth.

3. Test a little bit deeper than only comparing the current snapshots and the previous generate ones will be appreciated. For example, in the `defaultProps/with a few items/renders list properly` test, you could count the list cells to check if the cell amount matches the length of the test array,  `USER_ITEMS`, that you created in the test. You could also loop through the list cells, and get the text value of  `<Text/>` component to compare with the default PagintableList cell text value.

4. We are integrating Enzyme into the test. Enzyme provides additional testing utilities to interact with elements, which will be the next step that we are looking for in the future. Please feel free to use Enzyme if it helps with your tests.

Thank you very much for your effort in contributing to the PagintableList library. We appreciate it a lot and your name will be added into contributors in the next released version.

**Comment by sunkibaek** [comment]
Hi @BeckyWu220 , thanks for the feedback! Let me work on those and get back to you soon :-) !

**Comment by BeckyWu220** [comment]
@sunkibaek Thank you!

**Comment by sunkibaek** [comment]
Hi, @BeckyWu220, I thought I would reflect your feedback and change or add tests as follow:

> 1. In package.json file, please add "modulePathIngnorePatterns" in the "jest", make its value "/PaginatableListExample". This will limit the test scope to only the library code instead of both library code and example code.

-> Done! (although it sounds like you meant to use `testMatch` ... but not sure 🤷‍♂)

> 2. Please rename the index.test.js into ui.test.js and regenerate the snapshot if necessary. This will help us split the test code properly. Later, we could have API related test, Redux Store related test, and so forth.

-> Done!

> 3. Test a little bit deeper than only comparing the current snapshots and the previous generate ones will be appreciated. For example, in the defaultProps/with a few items/renders list properly test, you could count the list cells to check if the cell amount matches the length of the test array, USER_ITEMS, that you created in the test. You could also loop through the list cells, and get the text value of <Text/> component to compare with the default PagintableList cell text value.

-> Done!

> 4. We are integrating Enzyme into the test. Enzyme provides additional testing utilities to interact with elements, which will be the next step that we are looking for in the future. Please feel free to use Enzyme if it helps with your tests.

-> Sounds good! But in this particular case, I did not need it. And also consider: https://github.com/testing-library/react-testing-library

Let me know if there is anything else to improve 😄

**Comment by BeckyWu220** [comment]
Hi, @sunkibaek. Thanks for updating the PR. The tests are much detailed and we appreciate your comments about using `testID` in the `index.js` file. 

If you could fix the typo `redner` in`testID="default-redner-item"` to `render`, and make sure that the rest code that remains the same does not get highlighted as changes, we would be good to go.
 
PS: I'm not quite sure why a lot of code got highlighted even if the code remains the same. Please check the screenshots attached below. 
image

Thanks again.

**Comment by sunkibaek** [comment]
@BeckyWu220 Typos are fixed 😎 

Those highlights are deleted tangling whitespaces -- my editor automatically deletes those.

Speaking of formats of codes, it seems like the project has the `.prettierrc` file but not formatted with prettier. Any reasons for that?

**Comment by BeckyWu220** [comment]
@sunkibaek Thanks for reminding us. The Prettier had been properly set up in the project. Please rebase `master` branch, and run `npm run format` to format the code with predefined Prettier rules. This should help to resolve the formatting issue. Please let me know when you are done with it. Hopefully, we could merge your code very soon. Thanks!

**Comment by sunkibaek** [comment]
@BeckyWu220 rebasing is done!

**Comment by BeckyWu220** [comment]
@sunkibaek The PR had been merged! Thank you for your contribution. If you are available to keep working on more unit tests, we would be glad to discuss with you for the next steps. We will add you to the contributor list soon. Cheers!

**Pull request merged**
