### PR TITLE
13 core pagination

### LINKED ISSUE #13: Core Pagination Functionality Unit Test
Test the two core functionalities, which are loadMore and refresh in the PaginatableList. In order to achieve the testing, mock-up API responses need to be used in the test. 

- [ ] When loadMore method is called, mock-up API response, and check if the API call is properly called once with the correct parameters (pageNumber, pageSize, headers).
- [ ]  If onLoadMore props exist, test the value of onLoadMore, which is a function, is called properly with correct params (including additional query params). 

- [ ] When refresh method is called, mock-up API response, and check if the API call is made with the first page, along with correct parameters(pageSize, headers). 
- [ ] When onRefresh props exist, test the value of onRefresh to be called with proper params(pageSize, headers, additional query params).

### PR DESCRIPTION
**Pull request by sunkibaek**
Closes #13 

- Added test for `onLoadMore` and `onRefresh`.
- Used enzyme to dig into the connected component.

p.s.

`yarn.lock` has been added accidentally -- do you have any reasons not to include on in the repository? (either `package-lock.json` or `yarn.lock`)

It seems prettier formatted `package.json` file 🤔

### CODE REVIEW

**Comment by BeckyWu220** [comment]
@sunkibaek Thanks for your PR, we will review it soon. We will investigate the issues you brought up and get back to once it's sorted out.

**Comment by BeckyWu220** [comment]
Hi! @sunkibaek Thanks for your PR. We've reviewed it and here are a few questions. 

Line 184 of test `#onLoadMore/without custom onLoadMore/calls paginationStateManage.loadMore with proper parameters`, you have `PaginatableList` instance calls function `onLoadMore()`. Could you explain why you are calling it manually here? 
```
instance.onLoadMore()
```
From our perspective, `onLoadMore()` is called in the `PaginatableList` component itself while mounting in order to fetch the first page of list items. If you manually called the `onLoadMore()` again in the test, it would fetch the second page of data. If we understood your intention correctly, you were trying to check if the first call of `onLoadMore()` is called with proper parameters. In this case, you don't need to call `onLoadMore()` manually, because it will end up invoking the same method twice. You might want to declare the `loadMore` mock function earlier before shallowing the `PaginatableList`, and assign it to `pagintableStateManager.loadMore`, so you can do the same assert without manually calling `onLoadMore()`.

Another thing we noticed is that you only checked the `pageNumber` to be a Number type. It would be better if you could check it equals `0`, which is the default first page number defined in the list. And your manual function invoking could be used to check if the page number is increased properly after `onLoadMore()` is called multiple times. 

Same questions for the test of `#onRefresh`.

Please let us know if it makes senses to you, and we are more than happy to discuss further with you about the best unit test practices. Good job in naming the tests in a very descriptive way. Thanks!

**Comment by sunkibaek** [comment]
Hi @BeckyWu220 . Thanks for the feedback. They are valid concerns but here are some of my reasons:

You are correct that my intention was to call the method manually. Since we are defining an individual unit test per each method, I thought it was a good idea to call each method manually. I understand the method is being called when the component is mounted -- but what if the situation changes and we decide not to call the method in `componentDidMount`? The test will fail -- even without any changes of the codes in the method. By calling the method manually, I thought we can make a more isolated environment to unit-test the method.

The same logic goes with checking on the `pageNumber` -- since the `pageNumber` increases by the time we call the method manually, we cannot specify its value without considering the fact that the component lifecycle will call the method. I thought checking the type of the parameter is good enough for this case.

If we were aiming for request tests or integration tests -- which we use to see if different parts of the program work together well or not -- I might have not called the method manually. But in this case, we are trying to do unit-tests, so I thought manually calling them was the best strategy 😄 

Let me know if this makes any sense to you guys~!

Thanks!

**Comment by BeckyWu220** [comment]
@sunkibaek Thanks for your explaining. It makes sense to manually invoke the `onLoadMore()` with your consideration. If we target at testing `onLoadMore`, let's [disable the life cycle method](https://airbnb.io/enzyme/docs/api/ShallowWrapper/shallow.html) in `shallow`. In this way, we could more focus on the functionality of `onLoadMore` without being confused by the `onLoadMore` called in `componentDidMount` life cycle method. Please let me know if it makes sense to you. Thank you!

**Comment by sunkibaek** [comment]
@BeckyWu220 Yes, that makes sense! I did not know `enzyme` offers such functionality. Fixed as you mentioned!

**Comment by BeckyWu220** [comment]
@sunkibaek  Sorry for getting back late. The PR had been merged. We'd like to thank you for taking your time contributing to the library. We appreciate your patience and enjoy discussing with you about best practices in doing unit tests. Your name and profile picture had been added into external contributors list in the ReadMe file. If you are interested in contributing more, please let us know. Thank you!

**Pull request merged**
